// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: package.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_package_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_package_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_package_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_package_2eproto {
  static const uint32_t offsets[];
};
namespace QRCodePackage {
class Package;
struct PackageDefaultTypeInternal;
extern PackageDefaultTypeInternal _Package_default_instance_;
}  // namespace QRCodePackage
PROTOBUF_NAMESPACE_OPEN
template<> ::QRCodePackage::Package* Arena::CreateMaybeMessage<::QRCodePackage::Package>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace QRCodePackage {

enum Package_PackageType : int {
  Package_PackageType_HEAD = 0,
  Package_PackageType_HASH = 1,
  Package_PackageType_NAME = 2,
  Package_PackageType_DATA = 3,
  Package_PackageType_BACK = 4,
  Package_PackageType_FINI = 5,
  Package_PackageType_Package_PackageType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Package_PackageType_Package_PackageType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Package_PackageType_IsValid(int value);
constexpr Package_PackageType Package_PackageType_PackageType_MIN = Package_PackageType_HEAD;
constexpr Package_PackageType Package_PackageType_PackageType_MAX = Package_PackageType_FINI;
constexpr int Package_PackageType_PackageType_ARRAYSIZE = Package_PackageType_PackageType_MAX + 1;

const std::string& Package_PackageType_Name(Package_PackageType value);
template<typename T>
inline const std::string& Package_PackageType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Package_PackageType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Package_PackageType_Name.");
  return Package_PackageType_Name(static_cast<Package_PackageType>(enum_t_value));
}
bool Package_PackageType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Package_PackageType* value);
// ===================================================================

class Package final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:QRCodePackage.Package) */ {
 public:
  inline Package() : Package(nullptr) {}
  ~Package() override;
  explicit PROTOBUF_CONSTEXPR Package(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Package(const Package& from);
  Package(Package&& from) noexcept
    : Package() {
    *this = ::std::move(from);
  }

  inline Package& operator=(const Package& from) {
    CopyFrom(from);
    return *this;
  }
  inline Package& operator=(Package&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Package& default_instance() {
    return *internal_default_instance();
  }
  static inline const Package* internal_default_instance() {
    return reinterpret_cast<const Package*>(
               &_Package_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Package& a, Package& b) {
    a.Swap(&b);
  }
  inline void Swap(Package* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Package* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Package* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Package>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Package& from);
  void MergeFrom(const Package& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Package* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "QRCodePackage.Package";
  }
  protected:
  explicit Package(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  typedef Package_PackageType PackageType;
  static constexpr PackageType HEAD =
    Package_PackageType_HEAD;
  static constexpr PackageType HASH =
    Package_PackageType_HASH;
  static constexpr PackageType NAME =
    Package_PackageType_NAME;
  static constexpr PackageType DATA =
    Package_PackageType_DATA;
  static constexpr PackageType BACK =
    Package_PackageType_BACK;
  static constexpr PackageType FINI =
    Package_PackageType_FINI;
  static inline bool PackageType_IsValid(int value) {
    return Package_PackageType_IsValid(value);
  }
  static constexpr PackageType PackageType_MIN =
    Package_PackageType_PackageType_MIN;
  static constexpr PackageType PackageType_MAX =
    Package_PackageType_PackageType_MAX;
  static constexpr int PackageType_ARRAYSIZE =
    Package_PackageType_PackageType_ARRAYSIZE;
  template<typename T>
  static inline const std::string& PackageType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, PackageType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function PackageType_Name.");
    return Package_PackageType_Name(enum_t_value);
  }
  static inline bool PackageType_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      PackageType* value) {
    return Package_PackageType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 2,
    kIdFieldNumber = 1,
    kLenFieldNumber = 3,
    kTypeFieldNumber = 4,
  };
  // bytes data = 2;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // int32 id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // int32 len = 3;
  void clear_len();
  int32_t len() const;
  void set_len(int32_t value);
  private:
  int32_t _internal_len() const;
  void _internal_set_len(int32_t value);
  public:

  // .QRCodePackage.Package.PackageType type = 4;
  void clear_type();
  ::QRCodePackage::Package_PackageType type() const;
  void set_type(::QRCodePackage::Package_PackageType value);
  private:
  ::QRCodePackage::Package_PackageType _internal_type() const;
  void _internal_set_type(::QRCodePackage::Package_PackageType value);
  public:

  // @@protoc_insertion_point(class_scope:QRCodePackage.Package)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
    int32_t id_;
    int32_t len_;
    int type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_package_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Package

// int32 id = 1;
inline void Package::clear_id() {
  _impl_.id_ = 0;
}
inline int32_t Package::_internal_id() const {
  return _impl_.id_;
}
inline int32_t Package::id() const {
  // @@protoc_insertion_point(field_get:QRCodePackage.Package.id)
  return _internal_id();
}
inline void Package::_internal_set_id(int32_t value) {
  
  _impl_.id_ = value;
}
inline void Package::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:QRCodePackage.Package.id)
}

// bytes data = 2;
inline void Package::clear_data() {
  _impl_.data_.ClearToEmpty();
}
inline const std::string& Package::data() const {
  // @@protoc_insertion_point(field_get:QRCodePackage.Package.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Package::set_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:QRCodePackage.Package.data)
}
inline std::string* Package::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:QRCodePackage.Package.data)
  return _s;
}
inline const std::string& Package::_internal_data() const {
  return _impl_.data_.Get();
}
inline void Package::_internal_set_data(const std::string& value) {
  
  _impl_.data_.Set(value, GetArenaForAllocation());
}
inline std::string* Package::_internal_mutable_data() {
  
  return _impl_.data_.Mutable(GetArenaForAllocation());
}
inline std::string* Package::release_data() {
  // @@protoc_insertion_point(field_release:QRCodePackage.Package.data)
  return _impl_.data_.Release();
}
inline void Package::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  _impl_.data_.SetAllocated(data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:QRCodePackage.Package.data)
}

// int32 len = 3;
inline void Package::clear_len() {
  _impl_.len_ = 0;
}
inline int32_t Package::_internal_len() const {
  return _impl_.len_;
}
inline int32_t Package::len() const {
  // @@protoc_insertion_point(field_get:QRCodePackage.Package.len)
  return _internal_len();
}
inline void Package::_internal_set_len(int32_t value) {
  
  _impl_.len_ = value;
}
inline void Package::set_len(int32_t value) {
  _internal_set_len(value);
  // @@protoc_insertion_point(field_set:QRCodePackage.Package.len)
}

// .QRCodePackage.Package.PackageType type = 4;
inline void Package::clear_type() {
  _impl_.type_ = 0;
}
inline ::QRCodePackage::Package_PackageType Package::_internal_type() const {
  return static_cast< ::QRCodePackage::Package_PackageType >(_impl_.type_);
}
inline ::QRCodePackage::Package_PackageType Package::type() const {
  // @@protoc_insertion_point(field_get:QRCodePackage.Package.type)
  return _internal_type();
}
inline void Package::_internal_set_type(::QRCodePackage::Package_PackageType value) {
  
  _impl_.type_ = value;
}
inline void Package::set_type(::QRCodePackage::Package_PackageType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:QRCodePackage.Package.type)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace QRCodePackage

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::QRCodePackage::Package_PackageType> : ::std::true_type {};

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_package_2eproto
